; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = t-dongle-s3
src_dir = firmware/StingrayInventoryESP32
boards_dir = boards

[env:esp32-2432s028]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = COM28
upload_port = COM28
targets = upload
lib_deps =
  ricmoo/QRCode@^0.0.1
build_flags =
  -DSTINGRAY_BOARD_NAME=\"ESP32-2432S028\"
  -DSTINGRAY_SD_SPI_CS=5
  -DSTINGRAY_SD_SPI_SCK=18
  -DSTINGRAY_SD_SPI_MISO=19
  -DSTINGRAY_SD_SPI_MOSI=23

[env:t-dongle-s3]
platform = espressif32
board = dongles3
framework = arduino
monitor_speed = 115200
monitor_port = COM31
upload_port = COM31
targets = upload
lib_deps =
  ricmoo/QRCode@^0.0.1
  fastled/FastLED@^3.10.3
  adafruit/Adafruit GFX Library@^1.12.1
  adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DSTINGRAY_USE_SD_MMC
  -DSTINGRAY_BOARD_NAME=\"LILYGO_T_DONGLE_S3\"
  -DSTINGRAY_SD_MMC_CLK=12
  -DSTINGRAY_SD_MMC_CMD=16
  -DSTINGRAY_SD_MMC_D0=14
  -DSTINGRAY_SD_MMC_D1=17
  -DSTINGRAY_SD_MMC_D2=21
  -DSTINGRAY_SD_MMC_D3=18
